import fs from 'node:fs';
import path from 'node:path';
import type { IncomingMessage, ServerResponse } from 'node:http';
import type { Plugin, ResolvedConfig } from 'vite';
import { POSTER_FILENAME_RE } from '../core/poster';

const TEXTURE_RELATIVE_RE = /^([A-Za-z0-9._-]+\/)+[A-Za-z0-9._-]+\.png$/;

const POSTER_PREFIX = '/@screenframe/poster/';
const TEXTURE_PREFIX = '/@screenframe/texture/';
const POSTER_MAX_BYTES = 2 * 1024 * 1024;
const TEXTURE_MAX_BYTES = 12 * 1024 * 1024;
const POSTER_IMAGE_RE = /\.(webp|png|jpe?g)$/i;
const BOOT_NAME = 'boot.js';

export interface ScreenframePluginOptions {
  /** Directory, relative to the Vite root, where captured posters are written. */
  postersDir?: string;
  /** Directory, relative to the Vite root, where extracted device textures are written. */
  texturesDir?: string;
  /** When false, skip generating `boot.js` for folder-wide poster preload. */
  posterBoot?: boolean;
}

function postersPublicBase(postersDir: string): string {
  const trimmed = postersDir.replace(/\\/g, '/').replace(/\/$/, '');
  const withoutPublic = trimmed.replace(/^public\/?/, '');
  return `/${withoutPublic}`;
}

function listPosterFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => POSTER_IMAGE_RE.test(name))
    .sort();
}

function posterBootScript(files: string[], publicBase: string): string {
  return `/* generated by screenframe3d/vite — do not edit */
(function (g) {
  var BASE = (function () {
    var script = document.currentScript;
    if (script && script.src) return script.src.replace(/[^/]+$/, '');
    return ${JSON.stringify(`${publicBase}/`)};
  })();
  var FILES = ${JSON.stringify(files)};
  function safeStem(value, fallback) {
    var stem = String(value || '').replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '');
    return stem || fallback;
  }
  function screenshotStem(screenshot) {
    var path = String(screenshot || '').split('?')[0].split('#')[0];
    var baseName = path.split('/').pop() || 'screenshot';
    return safeStem(baseName.replace(/\\.[a-z0-9]+$/i, ''), 'screenshot');
  }
  function deviceStem(device) {
    return safeStem(String(device || '').split('?')[0].split('#')[0], 'device');
  }
  g.screenframeMatchPoster = function (look) {
    if (!look) return null;
    var prefix = screenshotStem(look.screenshot) + '--' + deviceStem(look.device) + '--';
    for (var i = 0; i < FILES.length; i++) {
      if (FILES[i].indexOf(prefix) === 0) return BASE + FILES[i];
    }
    return null;
  };
  for (var i = 0; i < FILES.length; i++) {
    var link = document.createElement('link');
    link.rel = 'preload';
    link.as = 'image';
    link.href = BASE + FILES[i];
    document.head.appendChild(link);
  }
})(typeof window !== 'undefined' ? window : this);
`;
}

function writePostedFile(
  req: IncomingMessage,
  res: ServerResponse,
  destPath: string,
  maxBytes: number,
  skipIfExists: boolean,
  onWrite?: () => void
): void {
  if (skipIfExists && fs.existsSync(destPath)) {
    res.statusCode = 204;
    res.end();
    req.resume();
    return;
  }

  const chunks: Buffer[] = [];
  let size = 0;
  let aborted = false;

  req.on('data', (chunk: Buffer) => {
    if (aborted) return;
    size += chunk.length;
    if (size > maxBytes) {
      aborted = true;
      res.statusCode = 413;
      res.end('File too large');
      req.destroy();
      return;
    }
    chunks.push(chunk);
  });
  req.on('end', () => {
    if (aborted) return;
    fs.mkdirSync(path.dirname(destPath), { recursive: true });
    fs.writeFileSync(destPath, Buffer.concat(chunks));
    onWrite?.();
    res.statusCode = 204;
    res.end();
  });
}

function writePosterBoot(dir: string, publicBase: string): string[] {
  fs.mkdirSync(dir, { recursive: true });
  const files = listPosterFiles(dir);
  fs.writeFileSync(path.join(dir, BOOT_NAME), posterBootScript(files, publicBase));
  return files;
}

function resolveInside(base: string, relative: string): string | null {
  const root = path.resolve(base);
  const abs = path.resolve(root, relative);
  const prefix = root.endsWith(path.sep) ? root : root + path.sep;
  if (abs !== root && !abs.startsWith(prefix)) return null;
  return abs;
}

/**
 * During `vite dev`, writes posters into `public/posters` and extracted
 * device textures into `public/textures`.
 */
export function screenframe(options: ScreenframePluginOptions = {}): Plugin {
  const postersDir = options.postersDir ?? 'public/posters';
  const texturesDir = options.texturesDir ?? 'public/textures';
  const posterBoot = options.posterBoot !== false;
  let root = process.cwd();

  const postersAbs = () => path.resolve(root, postersDir);
  const texturesAbs = () => path.resolve(root, texturesDir);
  const publicBase = () => postersPublicBase(postersDir);
  const refreshBoot = () => {
    if (posterBoot) writePosterBoot(postersAbs(), publicBase());
  };

  return {
    name: 'screenframe3d',
    configResolved(config: ResolvedConfig) {
      root = config.root;
    },
    buildStart() {
      refreshBoot();
    },
    configureServer(server) {
      refreshBoot();

      server.middlewares.use((req, res, next) => {
        if (req.method !== 'PUT' || !req.url) {
          next();
          return;
        }

        const url = req.url.split('?')[0] || '';

        if (url.startsWith(POSTER_PREFIX)) {
          const fileName = decodeURIComponent(url.slice(POSTER_PREFIX.length));
          if (!POSTER_FILENAME_RE.test(fileName)) {
            res.statusCode = 400;
            res.end('Invalid poster name');
            return;
          }
          writePostedFile(
            req,
            res,
            path.join(postersAbs(), fileName),
            POSTER_MAX_BYTES,
            false,
            refreshBoot
          );
          return;
        }

        if (url.startsWith(TEXTURE_PREFIX)) {
          const relative = decodeURIComponent(url.slice(TEXTURE_PREFIX.length));
          if (!TEXTURE_RELATIVE_RE.test(relative)) {
            res.statusCode = 400;
            res.end('Invalid texture path');
            return;
          }
          const dest = resolveInside(texturesAbs(), relative);
          if (!dest) {
            res.statusCode = 400;
            res.end('Invalid texture path');
            return;
          }
          writePostedFile(req, res, dest, TEXTURE_MAX_BYTES, true);
          return;
        }

        next();
      });
    },
  };
}

export default screenframe;
