/* generated by screenframe3d/vite — do not edit */
(function (g) {
  var BASE = (function () {
    var script = document.currentScript;
    if (script && script.src) return script.src.replace(/[^/]+$/, '');
    return "/posters/";
  })();
  var FILES = ["a48c3cc2-1fda-4ff9-9e6b-f17ff1c7c1ac--apple-iphone-12-pro--95371671.webp","a48c3cc2-1fda-4ff9-9e6b-f17ff1c7c1ac--apple-iphone-5s--f8bfab0c.webp","d7392066-2ef8-4dc4-8236-363e31d9601d--apple-iphone-12-pro--95371671.webp","d7392066-2ef8-4dc4-8236-363e31d9601d--apple-iphone-17-pro--6eea440e.webp","d7392066-2ef8-4dc4-8236-363e31d9601d--apple-iphone-5s--f8bfab0c.webp","ee7152ca-6be3-4ce6-8e5d-c2b649087dc4--apple-iphone-12-pro--95371671.webp","ee7152ca-6be3-4ce6-8e5d-c2b649087dc4--apple-iphone-14-pro--5baa057f.webp","ee7152ca-6be3-4ce6-8e5d-c2b649087dc4--apple-iphone-17-pro--6eea440e.webp","ee7152ca-6be3-4ce6-8e5d-c2b649087dc4--apple-iphone-5s--f8bfab0c.webp","sample-screenshot--apple-iphone-12-pro--95371671.webp","sample-screenshot--apple-iphone-12-pro--9990e9db.webp","sample-screenshot--apple-iphone-12-pro--e5d4fa53.webp","sample-screenshot--apple-iphone-14-pro--5baa057f.webp","sample-screenshot--apple-iphone-17-pro--46787a.webp","sample-screenshot--apple-iphone-17-pro--6eea440e.webp","sample-screenshot--apple-iphone-17-pro--ef354fba.webp","sample-screenshot--apple-iphone-5s--4270cc8c.webp","sample-screenshot--apple-iphone-5s--cbb9a530.webp","sample-screenshot--apple-iphone-5s--f8bfab0c.webp","screenframe-app--apple-iphone-12-pro--d06cf625.webp","screenframe-app--apple-iphone-13-pro--9f93c2f0.webp","screenframe-app--apple-iphone-14-pro--8fc14f8f.webp","screenframe-app--apple-iphone-17-pro--63523a7c.webp","screenframe-app--apple-iphone-5s--99b46c06.webp"];
  function safeStem(value, fallback) {
    var stem = String(value || '').replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '');
    return stem || fallback;
  }
  function screenshotStem(screenshot) {
    var path = String(screenshot || '').split('?')[0].split('#')[0];
    var baseName = path.split('/').pop() || 'screenshot';
    return safeStem(baseName.replace(/\.[a-z0-9]+$/i, ''), 'screenshot');
  }
  function deviceStem(device) {
    return safeStem(String(device || '').split('?')[0].split('#')[0], 'device');
  }
  g.screenframeMatchPoster = function (look) {
    if (!look) return null;
    var prefix = screenshotStem(look.screenshot) + '--' + deviceStem(look.device) + '--';
    for (var i = 0; i < FILES.length; i++) {
      if (FILES[i].indexOf(prefix) === 0) return BASE + FILES[i];
    }
    return null;
  };
  for (var i = 0; i < FILES.length; i++) {
    var link = document.createElement('link');
    link.rel = 'preload';
    link.as = 'image';
    link.href = BASE + FILES[i];
    document.head.appendChild(link);
  }
})(typeof window !== 'undefined' ? window : this);
