/* generated by screenframe3d/vite — do not edit */
(function (g) {
  var BASE = (function () {
    var script = document.currentScript;
    if (script && script.src) return script.src.replace(/[^/]+$/, '');
    return "/posters/";
  })();
  var FILES = ["sample-screenshot--apple-iphone-12-pro--95371671.webp","sample-screenshot--apple-iphone-14-pro--5baa057f.webp","sample-screenshot--apple-iphone-17-pro--6eea440e.webp","sample-screenshot--apple-iphone-5s--f8bfab0c.webp","screenframe-app--apple-iphone-14-pro--8374954d.webp","screenframe-app--apple-iphone-14-pro--8fc14f8f.webp"];
  function safeStem(value, fallback) {
    var stem = String(value || '').replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '');
    return stem || fallback;
  }
  function screenshotStem(screenshot) {
    var path = String(screenshot || '').split('?')[0].split('#')[0];
    var baseName = path.split('/').pop() || 'screenshot';
    return safeStem(baseName.replace(/\.[a-z0-9]+$/i, ''), 'screenshot');
  }
  function deviceStem(device) {
    return safeStem(String(device || '').split('?')[0].split('#')[0], 'device');
  }
  function fnv1a(value) {
    var hash = 2166136261;
    for (var i = 0; i < value.length; i++) {
      hash ^= value.charCodeAt(i);
      hash = Math.imul(hash, 16777619);
    }
    return (hash >>> 0).toString(16);
  }
  function environmentKey(environment) {
    if (!environment || environment === 'greenwich-park') return '/env/greenwich_park_1k.hdr';
    if (environment === 'studio') return '/env/studio_small_08_1k.hdr';
    if (environment === 'sunset') return '/env/venice_sunset_1k.hdr';
    return String(environment);
  }
  function posterFileName(look) {
    var tilt = look.tilt || {};
    var settings = [
      look.device,
      environmentKey(look.environment),
      look.fov == null ? 45 : look.fov,
      look.zoom == null ? 1 : look.zoom,
      tilt.x || 0,
      tilt.y || 0,
      tilt.z || 0
    ].join('|');
    return screenshotStem(look.screenshot) + '--' + deviceStem(look.device) + '--' + fnv1a(settings) + '.webp';
  }
  g.screenframeMatchPoster = function (look) {
    if (!look) return null;
    var exact = posterFileName(look);
    for (var i = 0; i < FILES.length; i++) {
      if (FILES[i] === exact) return BASE + FILES[i];
    }
    return null;
  };
  for (var i = 0; i < FILES.length; i++) {
    var link = document.createElement('link');
    link.rel = 'preload';
    link.as = 'image';
    link.href = BASE + FILES[i];
    document.head.appendChild(link);
  }
})(typeof window !== 'undefined' ? window : this);
